#!/bin/bash

corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"

tput setaf 8 ; tput setab 5 ; tput bold ; printf '%30s%s%-15s\n' "INSTALANDO" ; tput sgr0

apt-get install bc;
apt-get install nano -y;
apt-get install htop;
apt-get install squid3 -y;
apt-get install screen -y;
apt-get install wget squid screen dos2unix python
apt-get install screenfetch -y;
rm .bashrc
rm screenfetch-dev
wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPNmaster/.bashrc
wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/screenfetch-dev
clear
pip install speedtest-cli;
apt-get install nethogs -y;
apt-get install nload;
apt-get install wget;
apt-get install screen;
apt-get install python -y
wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/pythonsocks.py
wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/Stunnel4 -O stunnel
apt-get -y --purge remove samba*;
apt-get -y --purge remove apache2*;
apt-get -y --purge remove sendmail*;
#apt-get -y --purge remove bind9*;
echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
echo 1 > /proc/sys/net/ipv4/ip_forward
sed -i '$ i\echo 1 > /proc/sys/net/ipv4/ip_forward' /etc/rc.local
sed -i '$ i\echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6' /etc/rc.local
sed -i '$ i\iptables -A INPUT -p tcp --dport 25 -j DROP' /etc/rc.local
sed -i '$ i\iptables -A INPUT -p tcp --dport 110 -j DROP' /etc/rc.local
sed -i '$ i\iptables -A OUTPUT -p tcp --dport 25 -j DROP' /etc/rc.local
sed -i '$ i\iptables -A OUTPUT -p tcp --dport 110 -j DROP' /etc/rc.local
sed -i '$ i\iptables -A FORWARD -p tcp --dport 25 -j DROP' /etc/rc.local
sed -i '$ i\iptables -A FORWARD -p tcp --dport 110 -j DROP' /etc/rc.local
 
rm CpuMonitor ClearCache UserMonitor OpenUDP SpeedTest Banner UserBackup UserCreate UserClear LimiterSSH MudarLimite MudarSenha ConfVPS ConfVPN MudarValidade VNC UserDel KernelControl DadosMonitor OpenVPN restservice menu menudev statusvpn MonitorTotal.sh 

clear
wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/monitorcpu -O /bin/CpuMonitor
chmod +x /bin/CpuMonitor

wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/LimpadorCache -O /bin/ClearCache
chmod +x /bin/ClearCache

wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/usermonitor -O /bin/UserMonitor
chmod +x /bin/UserMonitor

wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/OpenUdp -O /bin/OpenUDP
chmod +x /bin/OpenUDP

wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/TesteConexao -O /bin/SpeedTest
chmod +x /bin/SpeedTest

wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/Banner -O /bin/Banner
chmod +x /bin/Banner

wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/UserBackup -O /bin/UserBackup
chmod +x /bin/UserBackup

wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/UserCreate -O /bin/UserCreate
chmod +x /bin/UserCreate

wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/UserClear -O /bin/UserClear
chmod +x /bin/UserClear

wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/LimiterSSH -O /bin/LimiterSSH
chmod +x /bin/LimiterSSH


wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/MudarLimite -O /bin/MudarLimite
chmod +x /bin/MudarLimite

wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/MudarSenha -O /bin/MudarSenha
chmod +x /bin/MudarSenha

wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/ConfVps -O /bin/ConfVPS
chmod +x /bin/ConfVPS

wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/ConfVPN -O /bin/ConfVPN
chmod +x /bin/ConfVPN

wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/MudarValidade -O /bin/MudarValidade
chmod +x /bin/MudarValidade

wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/VNC -O /bin/VNC
chmod +x /bin/VNC

wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/UserDel -O /bin/UserDel
chmod +x /bin/UserDel

wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/KernelControl -O /bin/KernelControl
chmod +x /bin/KernelControl

wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/DadosMonitor -O /bin/DadosMonitor
chmod +x /bin/DadosMonitor

wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/OpenVPN -O /bin/OpenVPN
chmod +x /bin/OpenVPN

wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/restservice -O /bin/restservice
chmod +x /bin/restservice
 
wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/menu -O /bin/menu
chmod +x /bin/menu

wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/menudev -O /bin/menudev
chmod +x /bin/menudev

rm -rf /etc/ssh/sshd_config
wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/sshd_config2 -O /etc/ssh/sshd_config
wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/squidconf
chmod +x squidconf
./squidconf
wget https://raw.githubusercontent.com/ffontinele35/Script_SSH_OpenVPN/master/payloads -O /etc/payloads

sed -i '3i\127.0.0.1 /@Fontinele\' /etc/hosts
sleep 1
sed -i '4i\127.0.0.1 portalrecarga.vivo.com.br/recarga\' /etc/hosts
sleep 1
sed -i '5i\127.0.0.1 portalrecarga.vivo.com.br/controle\' /etc/hosts
sleep 1
sed -i '6i\127.0.0.1 navegue.vivo.com.br/pre\' /etc/hosts
sleep 1
sed -i '7i\127.0.0.1 navegue.vivo.com.br/controle\' /etc/hosts
sleep 1
sed -i '8i\127.0.0.1 www.whatsapp.com\' /etc/hosts
sed -i '9i\127.0.0.1 dns.whatsapp.net\' /etc/hosts
sed -i '10i\127.0.0.1 /?\' /etc/hosts
sleep 1

ssh-keygen -A

/etc/init.d/ssh restart
service ssh restart

/etc/init.d/squid3 restart
service squid3 restart
service squid restart
sleep 1
clear

echo "America/Sao_Paulo" > /etc/timezone
ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
dpkg-reconfigure --frontend noninteractive tzdata > /dev/null 2>&1
# menu
cd
echo "menu" >> .bash_profile
rm /root/install
cat /dev/null > ~/.bash_history && history -c && clear
echo -e "\033[1;31m• \033[1;32mINSTALACAO CONCLUIDA !\033[0m"
echo ""
echo -e "\033[1;31m• \033[1;32mENTRE NO SISTEMA DIGITANDO: \033[1;33mmenu\033[0m"
sleep 3
menu
