#!/bin/bash

clear
corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"

tput setaf 7 ; tput setab 4 ; tput bold ; printf '%30s%s%-10s\n' "____MENU DE EDIÇÕES ADMINISTRATIVAS____" ; tput sgr0
echo ""
echo -e OBS: Digite - menu - para acessar o PACK
echo -e "| 0|\033[01;31m• Editar OpenSSH\033[0m"
echo -e "| 1|\033[01;31m• Editar OpenVPN\033[0m"
echo -e "| 2|\033[01;31m• Editar Squid3 \033[1;33mDebian8/Ubuntu14\033[0m"
echo -e "| 3|\033[01;31m• Editar Squid3 \033[1;35mDebian9/Ubuntu16+\033[0m"
echo -e "| 4|\033[0;32m• Atualizar aplicativos do sistema\033[0m"
echo -e "| 5|\033[0;32m• Atualizar sistema operacional\033[0m"
echo -e "| 6|\033[01;31m• Alterar relogio do servidor\033[0m"
echo -e "| 7|\033[01;31m• Registros de erros do OpenVPN\033[0m"
echo -e "| 8|\033[01;31m• Limpar cache de escritas\033[0m"
echo -e "| 9|\033[01;31m• Lista de payloads|hosts do Squid3\033[0m"
echo -e "|10|\033[01;31m• Logs de acessos Squid3 \033[1;33mDebian8/Ubuntu14\033[0m"
echo -e "|11|\033[01;31m• Logs de acessos Squid3 \033[1;35mDebian9/Ubuntu16+\033[0m"
echo -e "|12|\033[01;31m• Trocar senha do root\033[0m"
echo -e "|13|\033[01;31m• Status de configuração de rede\033[0m"
echo -e "|14|\033[01;32m• Upgrade \033[1;35mUbuntu O.S.\033[0m"
echo -e "|15|\033[01;31m• Reboot (Reinicia o servidor)\033[0m"
echo -e "|16|\033[01;31m• ReiniciarServicos (SSH, VPN e ProxySquid)\033[0m"
echo -e Segure CTRL + X para fechar as edicoes.
echo -e Segure CTRL + C para fechar logs.
echo -e Escreva menu para voltar ao menu de gerenciamento.
echo""
read -p " Selecione a opção [0-16]: " opcao

case $opcao in
  menu)
  sleep 1
  menu;;
 0)
  nano /etc/ssh/sshd_config
  sleep 1
  menudev;;
 1)
  nano /etc/openvpn/server.conf
  sleep 1
  menudev;;
 2)
  nano /etc/squid3/squid.conf
  sleep 1
  menudev;;
 3)
  nano /etc/squid/squid.conf
  sleep 1
  menudev;;
 4)
  apt-get update && apt-get upgrade -y
  sleep 1
  menudev;;
 5)
  apt-get dist-upgrade
  sleep 1
  menudev;;
 6)
  dpkg-reconfigure tzdata
  sleep 1
  menudev;;
 7)
  tail -f /var/log/syslog | grep ovpn-server
  sleep 1
  menudev;;
 8)
  cat /dev/null > ~/.bash_history && history -c
  sleep 1
  menudev;;
 9)
  nano /etc/payloads
  sleep 1
  menudev;;
 10)
  tail -f /var/log/squid3/access.log
  sleep 1
  menudev;;
 11)
  tail -f /var/log/squid/access.log
  sleep 1
  menudev;;
 12)
  passwd root
  sleep 1
  menudev;;
 13)
  ifconfig
  sleep 1
  menudev;;
 14)
  do-release-upgrade
  sleep 1
  menudev;;
 15)
 echo -e Reiniciando o servidor aguarde...
  reboot;;
 16)
  restservice
  sleep 1
  menudev;;
esac
