#!/bin/bash

clear
corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"

tput setaf 7 ; tput setab 4 ; tput bold ; printf '%30s%s%-10s\n' "MENU DE EDIÇÕES ADMINISTRATIVAS" ; tput sgr0
echo ""
echo -e "\033[0;32m| 0|\033[1;35mVoltar ao menu inicial\n"
echo -e "\033[0;32m| 1|\033[1;35m Editar OpenSSH \033[0;37m/etc/ssh/sshd_config\033[0m"
echo -e "\033[1;32m==================OPENVPN================\n"
echo -e "\033[0;32m| 2|\033[1;35m• Editar OpenVPN \033[0;37m/etc/openvpn/server.conf\033[0m"
echo -e "\033[0;32m| 3|\033[1;35m• Editar OpenVPN \033[0;37m/etc/openvpn/client-common.txt\033[0m"
echo -e "\033[0;32m| 4|\033[1;35m• Editar Hosts OpenVPN \033[0;37m/etc/hosts\033[0m"
echo -e "\033[0;32m| 5|\033[1;35m• Editar Payloads Squid \033[0;37m/etc/payloads\033[0m"
echo -e "\033[0;32m| 6|\033[1;35m• Registros de erros do OpenVPN\033[0m"
echo -e "\033[1;32m==================SQUID==================\n"
echo -e "\033[0;32m| 7|\033[1;35m• Editar Squid3 \033[0;37m/etc/squid3/squid.conf\033[0m"
echo -e "\033[0;32m| 8|\033[1;35m• Editar Squid \033[0;37m/etc/squid/squid.conf\033[0m"
echo -e "\033[0;32m| 9|\033[1;35m• Logs de acessos Squid3 \033[0;37m/var/log/squid3/access.log\033[0m"
echo -e "\033[0;32m|10|\033[1;35m• Logs de acessos Squid \033[0;37m/var/log/squid/access.log\033[0m"
echo -e "\033[1;32m==================STUNNEL=================\n"
echo -e "\033[0;32m|11|\033[1;35m• Editar Stunnel4 \033[0;37m/etc/default/stunnel4\033[0m"
echo -e "\033[0;32m|12|\033[1;35m• Editar Stunne.conf \033[0;37m/etc/stunnel/stunnel.conf\033[0m"
echo -e "\033[1;32m==================SISTEMA================\n"
echo -e "\033[0;32m|13|\033[1;35m• Atualizar aplicativos do sistema\033[0m"
echo -e "\033[0;32m|14|\033[1;35m• Atualizar sistema operacional\033[0m"
echo -e "\033[0;32m|15|\033[1;35m• Alterar relogio do servidor \033[0;37mtzdata\033[0m"
echo -e "\033[0;32m|16|\033[1;35m• Trocar senha do root \033[0;33m CUIDADO\033[0m"
echo -e "\033[0;32m|17|\033[1;35m• Status de configuração de rede \033[0;37mifconfig\033[0m"
echo -e "\033[0;32m|18|\033[1;35m• \033[0;32mUpgrade \033[0;37mAtualizar versão do sistema \033[0;33mUBUNTU\033[0m"
echo -e "\033[1;32m==========PORTAS DO SISTEMA======================\n"
echo -e "\033[0;32m|19|\033[1;35m• Mudar porta OPENVPN \033[0;37m443 \033[1;31me \033[0;37mSSH 22\033[0m"
echo -e "\033[0;32m|20|\033[1;35m• Mudar porta SSH \033[0;37m443 \033[1;31me \033[0;37m22 \033[1;31mOPENVPN \033[0;37m1194\033[0m"
echo -e "\033[1;32m==========SISTEMA DE REINICIALIZACAO====\n"
echo -e "\033[0;32m|21|\033[1;35m• Reboot \033[0;37mReinicia o servidor\033[0m"
echo -e "\033[0;32m|22|\033[1;35m• ReiniciarServicos \033[0;37mSSH, VPN e ProxySquid\033[0m"
echo -e "\033[1;35m Segure CTRL + X + Y para fechar as edicoes.\n"
echo -e "\033[1;35m Segure CTRL + C para fechar logs.\n"

read -p " Selecione a opção [0-22]: " opcao

case $opcao in
  0)
echo -e "\033[0mvoltando ao menu..."
  sleep 3
  menu;;
 1)
  nano /etc/ssh/sshd_config
  sleep 1
  menudev;;
 2)
  nano /etc/openvpn/server.conf
  sleep 1
  menudev;;
 3)
  nano etc/openvpn/client-common.txt
  sleep 1
  menudev;;
 4)
  nano /etc/hosts
  sleep 1
  menudev;;
 5)
  nano /etc/payloads
  sleep 1
  menudev;;
 6)
  tail -f /var/log/syslog | grep ovpn-server
  sleep 1
  menudev;;
 7)
  nano /etc/squid3/squid.conf
  sleep 1
  menudev;;
 8)
  nano /etc/squid/squid.conf
  sleep 1
  menudev;;
 9)
  tail -f /var/log/squid3/access.log
  sleep 1
  menudev;;
 10)
  tail -f /var/log/squid/access.log
  sleep 1
  menudev;;
 11)
  nano /etc/default/stunnel4
  sleep 1
  menu;;
 12)
  nano /etc/stunnel/stunnel.conf
  sleep 1
  menudev;;
 13)
  apt-get update && apt-get upgrade -y
  sleep 1
  menudev;;
 14)
 apt-get dist-upgrade
 sleep 1
 menudev;;
 15)
 dpkg-reconfigure tzdata
 sleep 1
 menudev;;
 16)
  passwd root
  sleep 1
  menudev;;
 17)
  ifconfig
  sleep 1
  menudev;;
 18)
  do-release-upgrade
  sleep 1
  menudev;;
 19)
  ConfVPN
  sleep 1
  menudev;;
  20)
  ConfVPN
  sleep 1
  menudev;;
  21)
  echo -e Reiniciando o servidor aguarde...
  reboot;;
  22)
  restservice
  sleep 1
  menudev;;
esac
