#!/bin/bash
clear
corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"

tput setaf 7 ; tput setab 4 ; tput bold ; printf '%30s%s%-10s' "MENU OPENVPN E SSH" ; tput sgr0

echo ""
echo -e "\033[0;32m| 0|\033[1;35m• Sair \033[0;37m(Para sair do script)\033[0m"
echo -e "\033[0;32m| 1|\033[1;35m• UserCreate \033[0;37m(Criar usuarios SSH)\033[0m"
echo -e "\033[0;32m| 2|\033[1;35m• UserBackup \033[0;37m(Gerencia backup dos usuarios SSH)\033[0m"
echo -e "\033[0;32m| 3|\033[1;35m• CpuMonitor \033[0;37m(Monitora o uso da CPU, RAM e UPTIME)\033[0m"
echo -e "\033[0;32m| 4|\033[1;35m• UserMonitor \033[0;37m(Monitora os usuarios conectados)\033[0m"
echo -e "\033[0;32m| 5|\033[1;35m• DadosMonitor \033[0;37m(Monitora o uso de dados/Banda|in||out|)\033[0m"
echo -e "\033[0;32m| 6|\033[1;35m• VNC \033[0;37m(Ativa a interface gráfica no servidor)\033[0m"
echo -e "\033[0;32m| 7|\033[1;35m• ClearCache \033[0;37m(Limpa cache e swap da maquina)\033[0m"
echo -e "\033[0;32m| 8|\033[1;35m• OpenUDP \033[0;37m(Libera porta UDP p/ ligacão e jogos no HTTP)\033[0m"
echo -e "\033[0;32m| 9|\033[1;35m• SpeedTest \033[0;37m(Testa a velocidade de link do servidor)\033[0m"
echo -e "\033[0;32m|10|\033[1;35m• Banner \033[0;37m(Mensagem para usuario quando conectar)\033[0m"
echo -e "\033[0;32m|11|\033[1;35m• LimiterSSH \033[0;37m(Limita as conexoes SSH)\033[0m"
echo -e "\033[0;32m|12|\033[1;35m• MudarLimite \033[0;37m(Muda o limite dos usuario SSH)\033[0m"
echo -e "\033[0;32m|13|\033[1;35m• MudarSenha \033[0;37m(Muda a senha do usuario)\033[0m"
echo -e "\033[0;32m|14|\033[1;35m• MudarValidade \033[0;37m(Muda a data de validade do usuario)\033[0m"
echo -e "\033[0;32m|15|\033[1;35m• DeletarUsuario \033[0;37m(Deleta usuario)\033[0m"
echo -e "\033[0;32m|16|\033[1;35m• OpenVPN Instalador \033[0;37m(Só execute isso uma única vez)\033[0m"
echo -e "\033[0;32m|17|\033[1;35m• LimparVencidos \033[0;37m(Limpar usuarios vencidos)\033[0m"
echo -e "\033[0;32m|18|\033[1;35m• KernelControl \033[0;37m(Procurar update do Kernel ou Remove)\033[0m"
echo -e "\033[0;32m|19|\033[1;35m• Reboot \033[0;37m(Reinicia o servidor)\033[0m"
echo -e "\033[0;32m|20|\033[1;35m• ReiniciarServicos \033[0;37m(SSH, VPN e ProxySquid)\033[0m"
echo -e "\033[0;32m|21|\033[1;35m• SSL - \033[1;37m Para instalar SSL\n"
echo -e "\033[0;32m|22|\033[1;35m• Python \033[1;37m Instalar Proxy Socks \033[0m"
echo -e "\033[0;32m|23|\033[1;35m• menudev \033[1;37m- para ver opções de administrador"
echo -e""
echo -e "\033[0;32m OBS: Digite - \033[1;31mmenu \033[1;37m- para acessar este sistema"
echo""
read -p " Selecione a opção [0-23]: " opcao


case $opcao in
 
  menudev)
  menudev
  sleep 2
  CTRL + C
 0)
 echo -e "\033[1;35mvoltando ao Sistema\033[0m"
 sleep 2
 exit;;
 1)
  UserCreate
  sleep 1
  menu;;
 2)
  UserBackup
  sleep 1
  menu;;
 3)
  CpuMonitor;;
 4)
  UserMonitor;;
 5)
  DadosMonitor;;
 6)
  VNC
  sleep 1
  menu;;
 7)
  ClearCache
  sleep 1
  menu;;
 8)
  OpenUDP
  sleep 1
  menu;;
 9)
  SpeedTest
  echo ""
  echo -ne "\033[1;32mEnter..\033[0m"; read
  menu;;
 10)
  Banner
  sleep 1
  menu;;
 11)
  LimiterSSH
  sleep 1
  menu;;
 12)
  MudarLimite
  sleep 1
  menu;;
 13)
  MudarSenha
  sleep 1
  menu;;
 14)
  MudarValidade
  sleep 1
  menu;;
 15)
  UserDel
  sleep 1
  menu;;
 16)
  OpenVPN
  sleep 1
  menu;;
 17)
  UserClear
  sleep 1
  menu;;
 18)
  KernelControl
  sleep 1
  menu;;
 19)
 echo -e Reiniciando o servidor aguarde...
  reboot;;
 20)
  restservice
  sleep 1
  menu;;
  21)
  bash stunnel
  sleep 1
  menu;;
  22)
  screen python pythonsocks.py
 sleep 1
  menu;;
  23)
  menudev
  sleep 1
  menu;;
esac
