#!/bin/bash

clear
corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"


while :; do 
echo -e "\033[0;37m=×=×APARECERA SOMENTE SE HOUVER ALGUEM CONECTADO=×=×=×=×=\033[0;30m"

echo -e "\033[0;37m=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=\033[0;30m"
echo -e "\033[47;30m        USUÁRIOS            |          CONEXÕES         \033[0m"
echo -e "\033[0;37m=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=\033[0;30m"

monitor ()
{
while :; do 
clear
for _user in $(awk -F: '$3>=1000 {print $1}' /etc/passwd); do
if [[ ! -z $(cat /etc/openvpn/*.log|grep ,${_user},) ]]; then
echo -e "------------------------------"
_conn=$(cat /etc/openvpn/*.log|grep ,${_user},| wc -l)
echo -e "Usuário: $_user"
echo -e "Conexões: $_conn"
echo -e "------------------------------"
fi
done
sleep 3
done
}
monitor
