#!/bin/bash
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%50s%s%-20s\n' "BadVPN Setup 1.3 RneoX" ; tput sgr0
if [ ! -e "/bin/badvpn-udpgw" ]; then
cd $HOME
echo -e "\033[1;32mAGUARDE..." 
wget https://www.dropbox.com/s/tgkxdwb03r7w59r/badvpn-udpgw -o /dev/null
mv -f $HOME/badvpn-udpgw /bin/badvpn-udpgw
chmod 777 /bin/badvpn-udpgw
sleep 2
fi
if ps x | grep "badvpn"|grep -v grep 1>/dev/null 2>/dev/null; then
	screen -r -S "badvpn" -X quit
	screen -wipe 1>/dev/null 2>/dev/null
	echo -e "\033[1;31mBADVPN DESATIVADO"
	sleep 2
	menu
else
	screen -dmS badvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 1000 --max-connections-for-client 10
	sleep 1
	echo -e "\033[1;32mBADVPN ATIVADO"
	sleep 2
	menu
fi
